import './layout.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Liron Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <title>{'Liron\'s Portfolio'}</title>
      {/*<meta name={'description'} content={metadata.description!}/>*/}
      <meta name="google-site-verification" content="SGs-frs5hKyEYwSpisvYh-1xm9SErBfCR6d6ceAah1o" />
    </Head>
      <body className={`${inter.className} dark-mode`}>{children}</body>
    </html>
  )
}
